### ISSUE TITLE
session disconnected from server

### ISSUE THREAD

**Issue by anniegbryant** [hendersontrent/theft-webtool#38]
Tried running catch22 with the web tool with a 34 sample by 1,200 time point dataset and after running for ~20 minutes, got an error that the shiny session disconnected from the server

**Comment by hendersontrent** [comment]
Yeah very likely related to #10 . Can you please try with maybe half the time points or less?

**Comment by anniegbryant** [comment]
I just retried with 34 samples by 300 time points and it also disconnected from the server. Should I reduce the number of samples and/or reduce the number of time points further? Thanks!

**Comment by hendersontrent** [comment]
Hmmm.... It's likely due to the server for this app not having enough processing power (which I have to pay for). I was going to wait until the `theft` paper is out to commit to that, but 34 by 300 should work.... Maybe just try with something trivial, like 5 samples by 50 timepoints to make sure it isn't a computational error?

**Comment by anniegbryant** [comment]
I retried with a csv containing 5 samples x 50 timepoints and the shiny app still disconnected after ~20 minutes. The same dataset ran with catch22 in my local RStudio in < 1 second. Any suggestions?

**Comment by hendersontrent** [comment]
Definitely a bug on data that small. Wonder if it’s an issue with my new radiobuttoninput for the feature set… Investigating!
